char getlevch(short bp6,short bp8,short bpa);
void incpenalty(void);
short levplan(void);
short levof10(void);
void setdead(bool df);
void cleartopline(void);
void finish(void);
short randno(short n);
void game(void);
void maininit(void);
int mainprog(void);

extern short nplayers,diggers,curplayer,startlev;
extern bool levfflag;
extern char levfname[];
extern char pldispbuf[];
extern long randv;
extern char leveldat[8][10][15];
extern int gtime;
extern bool gauntlet,timeout,synchvid,unlimlives;
